version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/agent"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/backend/bruno"
    schedule:
      interval: "weekly"
